export default {
  'poke-index': 'poke-index',
  'Type': 'Type',
  'king': 'king',
  'raising': 'raising',
  'battle': 'battle',
  'tools': 'tools',
  'male': 'male',
  'female': 'female',
  'Gen': 'Gen',
  'Gen1': 'Gen1',
  'Gen2': 'Gen2',
  'Gen3': 'Gen3',
  'Gen4': 'Gen4',
  'Gen5': 'Gen5',
}
