const dic: Record<string, string> = {
  'poke-index': 'poke-index',
  'filter': 'filter',
  'Type': 'Type',
  'king': 'king',
  'raising': 'raising',
  'battle': 'battle',
  'tools': 'tools',
  'ability': 'ability',
  'egg group': 'egg group',
  'move': 'move',
  'base stats': 'base stats',
  'type defense': 'type defense',
  'evolution': 'evolution',
  'male': 'male',
  'female': 'female',
  'Gen': 'Gen',
  'Gen1': 'Gen1',
  'Gen2': 'Gen2',
  'Gen3': 'Gen3',
  'Gen4': 'Gen4',
  'Gen5': 'Gen5',
  'language': 'language',
  'type-effect': 'type-effect',
  'nature-effect': 'nature-effect',
  'move-list': 'move-list',
  'ability-list': 'ability-list',
  'egg-group-list': 'egg-group-list',
  'item-list': 'item-list',
  'data-sync': 'data-sync',
}

export default dic;
