export default {
  'poke-index': '全国图鉴',
  'Type': '属性',
  'king': '天王',
  'raising': '培育',
  'battle': '模拟',
  'tools': '工具',
  'male': '雄性',
  'female': '雌性',
  'Gen': '世代',
  'Gen1': '第1世代',
  'Gen2': '第2世代',
  'Gen3': '第3世代',
  'Gen4': '第4世代',
  'Gen5': '第5世代',
}
